parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Norvutec\UserGuideBundle\Component\UserGuide:
            tags: [ 'norvutec.user_guide.guide' ]

    Norvutec\UserGuideBundle\Component\UserGuideRegistry:
        arguments: [ !tagged norvutec.user_guide.guide ]
        autowire: true