parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Norvutec\UserGuideBundle\Component\UserGuide:
            tags: [ 'norvutec.user_guide.guide' ]

    Norvutec\UserGuideBundle\Component\UserGuideRegistry:
        arguments: [ !tagged norvutec.user_guide.guide ]
        autowire: true
    Norvutec\UserGuideBundle\Component\UserGuideHandler:
        autowire: true

    Norvutec\UserGuideBundle\Command\:
        resource: '../src/Command'
        autowire: true
        tags: [ console.command ]
    Norvutec\UserGuideBundle\Controller\:
        resource: '../src/Controller'
        autowire: true

    Norvutec\UserGuideBundle\Twig\TemplateLoaderExtension:
        tags: [ 'twig.extension' ]
        autowire: true

    Norvutec\UserGuideBundle\Form\UserGuideFormExtension:
        tags: [ 'form.type_extension' ]